version: "3.4"
services:
  data-workspace-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    image: data-workspace-test
    env_file:
      - ./.envs/test.env
    ports:
      - "8000"
    links:
      - "data-workspace-postgres"
      - "data-workspace-redis"
    extra_hosts:
      - "dataworkspace.test:127.0.0.1"
      - "testapplication-23b40dd9.dataworkspace.test:127.0.0.1"
      - "testvisualisation.dataworkspace.test:127.0.0.1"
      - "testvisualisation--58d9e87e.dataworkspace.test:127.0.0.1"
      - "testvisualisation-a.dataworkspace.test:127.0.0.1"
      - "testvisualisation-b.dataworkspace.test:127.0.0.1"
      - "api.ecr.my-region-1.amazonaws.com:127.0.0.1"
  data-workspace-postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    image: data-workspace-postgres
    ports:
      - "5432"
  data-workspace-redis:
    build:
      context: redis
      dockerfile: Dockerfile
    image: data-workspace-redis
    ports:
      - "6379"
